#!/usr/bin/env node
const { program, Command } = require("commander");
const packageJSON = require("../package.json");

program.command("germany", "Saying hello to Germany");

program.action(() => {
  console.log("Hello world");
});

program.parse(process.argv);
