#!/usr/bin/env node
const { program } = require("commander");
const packageJSON = require("../package.json");

program.version(packageJSON.version).action(() => {
    console.log("Hello world")
})

program.parse(process.argv);
