#!/usr/bin/env node
const { program } = require("commander");
const packageJSON = require("../package.json");

program.version(packageJSON.version);

program.action(() => {
  console.log("Hello world germany");
});

program.parse(process.argv);
