#!/usr/bin/env node
const { program, Command } = require("commander");
const packageJSON = require("../package.json");

program.version(packageJSON.version);
program.command("world", "Saying hello world");

program.action(() => {
  console.log("hello");
});

program.parse(process.argv);
